#!/bin/bash

# $$$$$$\  $$$$$$\   $$$$$$\  $$\      $$\ 
\_$$  _|$$  __$$\ $$  __$$\ $$$\    $$$ |
  $$ |  $$ /  \__|$$ /  $$ |$$$$\  $$$$ |
  $$ |  \$$$$$$\  $$$$$$$$ |$$\$$\$$ $$ |
  $$ |   \____$$\ $$  __$$ |$$ \$$$  $$ |
  $$ |  $$\   $$ |$$ |  $$ |$$ |\$  /$$ |
$$$$$$\ \$$$$$$  |$$ |  $$ |$$ | \_/ $$ |
\______| \______/ \__|  \__|\__|     \__|

# Update and upgrade the system
echo "Updating package list..."
apt update -y
echo "Upgrading packages..."
apt upgrade -y

# Install Docker Compose
echo "Installing Docker Compose..."
apt install docker-compose -y

# Install Neofetch
echo "Installing Neofetch..."
apt install neofetch -y

# Run Neofetch to display system information
echo "Running Neofetch..."
neofetch

# Install slim
echo "Installing slim

echo "All tasks completed successfully!"
