#!/bin/bash

# Install Slim
echo "Installing Slim..."
apt install slim -y
echo "Starting Slim..."
sudo service slim start

# Install Kde Plasma
echo "Installing Kde Plasma. GUI..."
apt install kde-plasma-desktop -y

# Install Firefox
echo "Installing Firefox..."
snap install firefox -y

# Install Spectacle
echo "Installing Spectacle"
apt install kde-spectacle -y

# Restart
echo "Rebooting..."
reboot


echo "All tasks completed successfully!"
