#!/bin/bash

# Install slim
echo "Installing Slim..."
sudo apt install slim
echo "Starting Slim..."
sudo service slim start

# Install Docker Compose
echo "Installing Docker Compose..."
apt install docker-compose -y

# Install Neofetch
echo "Installing Neofetch..."
apt install neofetch -y

# Run Neofetch to display system information
echo "Running Neofetch..."
neofetch

echo "All tasks completed successfully!"
